name: weather_forecast
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/weather/light_rain.png
    - assets/images/weather/partly_cloudy.png
    - assets/images/weather/rain_and_thunder.png
    - assets/images/weather/rainy.png
    - assets/images/weather/thunder.png
    - assets/images/weather/sunny.png